### PR TITLE
Add InstallationManager Listeners

### PR DESCRIPTION
**Pull request by marstr**
Adds the ability for applications to listen for the outcome of saving an installation.

### CODE REVIEW

**Comment by marstr** [comment]
I modeled this after Volley's mechanism for reporting the outcome of HTTP Requests. You can see an example of that here: https://developer.android.com/training/volley/simple#simple

**Comment by marstr** [comment]
I'm going to wait to fix the tests up until I get feedback on this mechanism in general. :)

**Comment by marstr** [comment]
Side note, I had been kinda thinking we didn't need `NotificationHub.getInstallationId` or `NotificationHub.getPushChannel` because it's is seemed like a scenario that was more likely to be needed in a sample application like our more than any other place. With callbacks like these, we can grab whatever detail we want about the installation after it's been saved without pollution the `NotificationHub` class.

However, I think the PR was the final straw that convinced me we need it. While it may still be true that it's only a developer feature, it's been extremely handy for me to get access to the Push Channel for when I was pinging the sample application from the Firebase Console. Plus, the Installation ID would have given me a lot of confidence that my installation had worked in the our portal Test Send page. (At the moment in only shows Registration handles.) So regardless of sample app or otherwise, I think if you're a developer adding NotificationHub to your app, getting access to this data without re-installing is valuable scenario.

**Comment by brannon** [comment]
@marstr 

> I had been kinda thinking we didn't need NotificationHub.getInstallationId or NotificationHub.getPushChannel 

We do need `getInstallationId` for sure. If an app developer wants to send a notification to a specific device, they need to know the installation ID. A pattern we've seen ACP developers use is to send the installation ID to their own backend so they can use it to send notifications.

**Comment by marstr** [comment]
> @marstr
> 
> > I had been kinda thinking we didn't need NotificationHub.getInstallationId or NotificationHub.getPushChannel
> 
> We do need `getInstallationId` for sure. If an app developer wants to send a notification to a specific device, they need to know the installation ID. A pattern we've seen ACP developers use is to send the installation ID to their own backend so they can use it to send notifications.

💯 I've seen the light, I totally agree.

**Comment by marstr** [comment]
Alright, today is the day! We're gearing up to release preview2, and I haven't heard any objections to merging this PR. I'm adding this in!

**Pull request merged**
